In [1]:
import numpy as np

In [14]:
matrix = np.random.randint(1, 90, (5, 5))
print("Matrix: ", matrix)

row_mean = np.mean(matrix, axis=1, dtype=int)
print("Row_mean", row_mean)

col_mean = np.mean(matrix, axis=0, dtype=int)
print("Col_mean: ", col_mean)

print("Sorted_row: ", np.sort(matrix, axis=1))
print("Sorted_col: ", np.sort(matrix, axis=0))

row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)
print("Sum of Row: ", row_sum)
print("Sum of Col: ", col_sum)

matrix = np.where(matrix % 2 == 0, -1, matrix)
print(matrix)

neg_count = np.sum(matrix < 0, axis=0)
print(neg_count)

Matrix:  [[23 73 63 11 22]
 [69 18 27 44 17]
 [34  3 64 31 65]
 [ 9 75 61 66 56]
 [86 66 12 21 73]]
Row_mean [38 35 39 53 51]
Col_mean:  [44 47 45 34 46]
Sorted_row:  [[11 22 23 63 73]
 [17 18 27 44 69]
 [ 3 31 34 64 65]
 [ 9 56 61 66 75]
 [12 21 66 73 86]]
Sorted_col:  [[ 9  3 12 11 17]
 [23 18 27 21 22]
 [34 66 61 31 56]
 [69 73 63 44 65]
 [86 75 64 66 73]]
Sum of Row:  [192 175 197 267 258]
Sum of Col:  [221 235 227 173 233]
[[23 73 63 11 -1]
 [69 -1 27 -1 17]
 [-1  3 -1 31 65]
 [ 9 75 61 -1 -1]
 [-1 -1 -1 21 73]]
[2 2 2 2 2]


In [25]:
mat_stock = np.random.randint(20, 80, (5, 5))
print("Stock: ", mat_stock)

mat_demand = np.random.randint(20, 80, (5, 5))
print("Demand: ", mat_demand)

remaining = mat_stock - mat_demand
print(remaining)

total_shortage = np.sum(np.where(remaining < 0, -remaining, 0))
print(total_shortage)

neg_values = np.where(remaining < 0, 0, remaining)
print(neg_values)

zero_stock = np.sum(np.where(remaining > 1, 1, remaining))
print(zero_stock)

print("Sorted_row: ", np.sort(remaining, axis=1))

Stock:  [[23 28 30 61 64]
 [41 74 53 39 42]
 [60 21 23 41 51]
 [56 60 47 33 60]
 [28 34 68 32 73]]
Demand:  [[59 40 23 23 48]
 [74 22 76 59 54]
 [60 68 27 45 39]
 [40 29 51 46 47]
 [25 71 49 22 77]]
[[-36 -12   7  38  16]
 [-33  52 -23 -20 -12]
 [  0 -47  -4  -4  12]
 [ 16  31  -4 -13  13]
 [  3 -37  19  10  -4]]
249
[[ 0  0  7 38 16]
 [ 0 52  0  0  0]
 [ 0  0  0  0 12]
 [16 31  0  0 13]
 [ 3  0 19 10  0]]
-238
Sorted_row:  [[-36 -12   7  16  38]
 [-33 -23 -20 -12  52]
 [-47  -4  -4   0  12]
 [-13  -4  13  16  31]
 [-37  -4   3  10  19]]


In [26]:
import pandas as pd

In [33]:
file_ = pd.read_csv('student_data.csv')

# print(file_.head(8))

print(file_.tail(8))

# print(file_)

      study_hours  attendance  sleep_hours  internet_usage  \
9992            5         100            9               2   
9993           10          86            9               9   
9994            4          53            7               8   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9992                      9              62      100.00           Placed  
9993                     15              63      100.00           Placed  
9994                     10              71       85.02           Placed  
9995                      8              88       69.31       Not Placed  
9996                      4              87      100.00           