In [3]:
import numpy as np

In [6]:
a = np.array([1, 3, 5, 0, 2])
print(a)

[1 3 5 0 2]


In [7]:
a = np.array([1, 3, 5, 0, 2, '4'])
print(a)

['1' '3' '5' '0' '2' '4']


In [9]:
# Question 1
np_arr = np.array([3, 3, 3, 3.3, 'Hello', False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


In [14]:
a = np.zeros([2, 3, 4], dtype=int)
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [15]:
a = np.empty(4, dtype=int)
print(a)

[          353782848                   0 3257854488033964338
 7004284026344453730]


In [16]:
a = np.full(3, 5, dtype=int)
print(a)

[5 5 5]


In [27]:
a = np.arange(2, 8, 2, dtype=int)
print(a)

[2 4 6]


In [26]:
a = np.linspace(0, 10, 3, dtype=int)
print(a)

[ 0  5 10]


In [30]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a.shape)

(2, 3)


In [31]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a.size)

6


In [42]:
a = np.random.randint(2, 8, size=5, dtype=int)
print(a)

[6 2 6 5 3]


In [43]:
a = np.random.choice(['Apple', 'Banana', 'Orange'])
print(a)

Banana


In [53]:
# BROADCASTING

a = np.array([4, 6, 12, 14])
b = np.array([2, 3, 6, 7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  9 18 21]
[2 3 6 7]
[ 8 18 72 98]
[2. 2. 2. 2.]


In [57]:
a = np.array([4, 6, 12, 14, 15])
b = np.array([2, 3, 6, 7])
print(a * b)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [60]:
a = np.random.randint(5, 15, 6)
print(a)
b = a.reshape([2, 3])
print(b)

[ 9  5  6 12  8  5]
[[ 9  5  6]
 [12  8  5]]


In [69]:
a = np.random.randint(5, 15, 6)

b = a.reshape(2, 3)
print(b)
print(b.T)

[[ 7  5  5]
 [ 5 14 14]]
[[ 7  5]
 [ 5 14]
 [ 5 14]]


In [72]:
a = np.random.randint(5, 15, 6)
b = np.random.randint(5, 15, 6)
c = np.concatenate((a, b))
print(a)
print(b)
print(c)

[ 8 14  9  7  5  5]
[ 8 10 13 10  5 12]
[ 8 14  9  7  5  5  8 10 13 10  5 12]


In [73]:
a = np.random.randint(5, 15, 6)
b = np.random.randint(5, 15, 6)
c = np.concatenate((a, b), axis=0)
print(a)
print(b)
print(c)

[9 9 9 7 9 6]
[10  7 12  8 12  8]
[ 9  9  9  7  9  6 10  7 12  8 12  8]


In [75]:
a = np.random.randint(5, 15, 6).reshape(2, 3)
b = np.random.randint(5, 15, 6).reshape(2, 3)
c = np.concatenate((a, b), axis=1)
print(a)
print(b)
print(c)

[[ 8  6 11]
 [ 8  7  8]]
[[ 5  5  6]
 [14 11  8]]
[[ 8  6 11  5  5  6]
 [ 8  7  8 14 11  8]]


In [78]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
c = np.where(b > 2, b, a)
print(a)
print(b)
print(c)

[ 7  9  3 13  5  9]
[11 13  9 11  3  1]
[11 13  9 11  3  9]


In [80]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.sort(a)
print(c)

[11 11  5  2 13  4]
[ 2  4  5 11 11 13]


In [82]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
print(a, b)
c = np.sum(a + b)
print(c)

[ 6 11 13  2  6  7] [ 2 15 16 16  5 12]
111


In [83]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.mean(a)
print(c)

[ 5 11  2 13 12  5]
8.0


In [85]:
a = np.random.randint(2, 15, 6)
print(a)
c = np.std(a)
print(c)

[11 13  3 12  9 12]
3.366501646120693


In [86]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))

[ 3  6 10  3  6  4]
3


In [87]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.max(a))

[ 3  4  5  2  3 12]
12


In [88]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.unique(a))

[12 14 10  3  6  8]
[ 3  6  8 10 12 14]


In [92]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)
print(a, b)
print(np.matmul(a, b))

[ 6 13  3  3  2 11] [ 9 17  1 12 13 18]
538


In [95]:
# Homework

# Copy concept

# A shop with different grocery items. Take 5 6 products alng with their prices, and perform operations.

scores = []
days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
for i in range(7):
  # x = input(f'Scores on days{i}');
  scores = [int(x) for x in scores]
  print(scores)